apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-docker
spec:
  replicas: 40
  selector:
    matchLabels:
      app: spring-boot-docker
  template:
    metadata:
      labels:
        app: spring-boot-docker
    spec:
      containers:
      - name: spring-boot-docker
        image: kshooter2000/spring-boot-docker-mem1g
        resources:
          requests:
            memory: "100Mi"
            cpu: "0.1"
        ports:
        - containerPort: 8080
